name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libasound2-dev libx11-dev libxcursor-dev libxrandr-dev libxi-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Install raylib from source
      run: |
        git clone --depth=1 https://github.com/raysan5/raylib.git
        cd raylib
        mkdir build && cd build
        cmake ..
        make -j2
        sudo make install
        cd ../..

    - name: Build
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Ensure assets folders exist
      run: |
        mkdir -p assets/fallback

    - name: Run tests
      run: |
        cd build/tests
        ctest --output-on-failure